#map information
map_width: 40
map_length: 100
BALLON_num: 6
AIMUAV_num: 1

#uart information
##/dev/pts/23
Listen_port : /dev/pts/20
#/dev/pts/24
Simulate_port : /dev/pts/21
#UAV information
UAV_filed: &1 11.539999999999999
UAV_speed: &2 0.0030000000000000001
#UAV1 information
start_point1: &3 
  - 16.666666
  - 0
  - 0
first_point1: &4
  - 16.666666
  - 20
  - 10
end_point1: &5
  - 0
  - 0
  - 0
UAV1:
  - *1
  - *2
  - *3
  - *4
  - *5
#UAV2 information
start_point2: &8
  - 49.999999
  - 0
  - 0
first_point2: &9
  - 49.999999
  - 20
  - 10
end_point2: &10
  - 0
  - 0
  - 0
UAV2:
  - *1
  - *2
  - *8
  - *9
  - *10
#UAV3 information
start_point3: &13
  - 83.333332
  - 0
  - 0
first_point3: &14
  - 83.333332
  - 20
  - 10
end_point3: &15
  - 0
  - 0
  - 0
UAV3:
  - *1
  - *2
  - *13
  - *14
  - *15
#Simulate AIM information
a: &16 30
b: &17 30
c: &18 50
d: &19 20
Simulate_speed: &20 0.002
Simulate_AIM:
  - *16
  - *17
  - *18
  - *19
  - *20
#ballon information
ballon_point1:
  - 0
  - 0
  - 0
ballon_point2:
  - 0
  - 0
  - 0
ballon_point3:
  - 0
  - 0
  - 0
ballon_point4:
  - 0
  - 0
  - 0
ballon_point5:
  - 0
  - 0
  - 0
ballon_point6:
  - 0
  - 0
  - 0